[package]
name = "vmesh"
version = "0.2.0"
authors = ["Rafał Harabień <rafalh92@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
base64 = "0.10"
serde_json = "1"
serde = "1"
serde_derive = "1"

[dependencies.gltf]
version = "0.15"
features = ["extras", "names", "utils", "KHR_materials_pbrSpecularGlossiness"]
default-features = false
